# Generated by Django 6.0.4 on 2026-06-13 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_contactmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='author_request',
            field=models.BooleanField(default=False),
        ),
    ]
